### ISSUE TITLE
Review of aggregate unit test queue term

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#10]
I didn't fully comprehend the use of `queue` in the following assertions, mainly since there's no reference to it within the [Aggregate class](https://github.com/meteor-space/event-sourcing/blob/3341c880c9789036f3beff79ab23db323beee010/source/domain/aggregate.coffee) 

[`appends the event to the queue`](https://github.com/meteor-space/event-sourcing/blob/3341c880c9789036f3beff79ab23db323beee010/tests/domain/aggregate.unit.coffee#L63) 

[`does not append the event to the queue if something fails`](https://github.com/meteor-space/event-sourcing/blob/3341c880c9789036f3beff79ab23db323beee010/tests/domain/aggregate.unit.coffee#L77)

Is this ["internal event queue of the aggregate "](https://github.com/meteor-space/event-sourcing/pull/9#discussion_r39742479) exclusively staging the event for committing?

`stages the event for committing`
`does not stage the event for committing if something fails`

**Comment by DominikGuzei** [comment]
Yeah sorry for that – it is just the array that holds the events that are generated by the aggregate before being saved by the repository :wink: What would you call that in the tests?

**Comment by rhyslbw** [comment]
Maybe `stages the event in memory` OR `pushes the event into the events array` ?

**Comment by DominikGuzei** [comment]
yeah i like the second one `pushes the event into the events array` as it is closest possible to the metal :wink:
