### ISSUE TITLE
Simple examples coming soon?

### ISSUE THREAD

**Issue by rdooh** [meteor-space/event-sourcing#36]
Would be nice to see a 'todo' demo or similar, or even just some code snippets in the documentation.  Very interesting project - thanks for tackling this!

**Comment by rhyslbw** [comment]
Hi @rdooh, thanks! We have a couple of examples to check out:

https://github.com/meteor-space/todos
https://github.com/meteor-space/donations

Documentation changes are on hold until we wrap up the latest round of development, but these examples are the best reference right now. We have an active Slack that's the best place to be if you're considering implementing. Send me a private message with an email address here https://gitter.im/meteor-space/general to get access.
