### ISSUE TITLE
Investigate failed commit processing timeouts

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#39]
According to a card in Trello authored by @DominikGuzei 

> Sometimes commits are still timing out in a weird way – although (IMO) everything went fine during processing.

- [x] Determine problem for the repeatable timeout
- [x] Fix problem, real-world test
- [x] Confirm there is a race potential with failing the commit
- [x] Protect against race condition before [failing the commit](https://github.com/meteor-space/event-sourcing/blob/master/source/server/infrastructure/commit_publisher.coffee#L83-L89)

**Comment by rhyslbw** [comment]
Since `CommitPublisher` is used as a singleton, it looks like our [current design is just overwriting the previous timer](https://github.com/meteor-space/event-sourcing/blob/master/source/server/infrastructure/commit_publisher.coffee#L58) with each new commit to publish right? I'd expect to see an array of timeouts tracking objects, commit id as the key, then once completed, the timeout cleared, and the tracker removed.

**Comment by rhyslbw** [comment]
Also, is it worth the performance hit to check that the commit is not already marked as processed before failing it? Would help with potential race conditions between processes

**Comment by DominikGuzei** [comment]
Yeah, we have to improve that design … i think it's fine when we really ensure that the timers are managed correctly.

**Comment by rhyslbw** [comment]
I think this is the problem: we’re assigning a reference to the setTimeout, but then each commit after steals the reference. Under low load and with blocking processing this would be cleared before the next commit is made, but if the next commit starts being published before the previous one has been completed, the reference is changed, so the first one doesn't cleared. Then, x minutes later it fails!

**Comment by rhyslbw** [comment]
I've confirmed the problem locally, and prepared a fix. Will submit PR tomorrow as I need to get some sleep!

**Comment by rhyslbw** [comment]
Fixed in #76, will be released very soon
