### ISSUE TITLE
Make Aggregates serializable for snapshotting

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#44]
via @DominikGuzei 

Currently the aggregates are basically creating customized snapshot classes for themselves which extend `Space.messaging.Serializable` and get their fields from the aggregate.

It would be much easier to make the aggregate class itself serializable and let the snapshotter serialize and deserialize it into and from the collection.

**Comment by rhyslbw** [comment]
@qejk just reviewed this, and I see it's what you were referring to. I agree this is the way to go

**Comment by rhyslbw** [comment]
@DominikGuzei Maybe we're better off exploring the option of just depreciating `Space.eventSourcing.Aggregate`. Wouldn't mixing [move the logic to `EventSourceable`](https://github.com/meteor-space/event-sourcing/issues/57) into Space.domain.Entity` give us the same result?

**Comment by DominikGuzei** [comment]
Yeah we can try to implement it via mixins … is probably a bit more work but worth it.

**Comment by rhyslbw** [comment]
Great, I's probably going to be about the same amount of effort prior to this discovery we had two issues. Closing this in favour of #57
