### ISSUE TITLE
Change Projector name and API to be more expressive

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#46]
- [x] `Projector` to `ProjectionRebuilder` - This class has nothing to do with standard projecting, only _rebuilding_
- [x] change `replay` to `rebuild`
- [x] `projection.enterReplayMode()` to `projection.enterRebuildMode()`
- [x] `projection.exitReplayMode()` to `projection.exitRebuildMode()`
- [x] change params for `rebuild`, first being an array of projections, second being for options
- [x] `projection._isInReplayMode` to a state prop
- [x] `isReplay` to `isRebuildEvent`

Thoughts @meteor-space/core ?

**Comment by DominikGuzei** [comment]
Sounds good to me! :+1:
