### ISSUE TITLE
eventCorrelationProperty is serialized as EJSON

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/event-sourcing#67]
```json
"meta" : {
  "nameOfMyEventCorrelationProperty" : {
    "EJSON$type" : "Guid",
    "EJSON$value" : "ac3fe7a9-b634-4be4-996c-24a16d151b3d"
    }
 },
```

**Comment by rhyslbw** [comment]
Is this really a bug, or would it just be nice to go `.toData()` for cleaner structure?

**Comment by darko-mijic** [comment]
Since deserialization works it could demoted to enhancement. But this is the only thing in the commit store serialized as EJSON.

**Comment by rhyslbw** [comment]
Great, just checking. I'm scoping the 3.1.0 release now, but as this is data-related I'll include it

**Comment by darko-mijic** [comment]
Great, I agree. It is not a bug but it is important since it changes data in the commit store.

**Comment by rhyslbw** [comment]
Should this be a string `toString()` or an object via `toData()`? If we go with the latter, you'd need to access the value via the value sub-property 
``` javascript
myEvent.meta[myCorrelationId].value
```
whereas with a string it would be the same as now:
``` javascript
myEvent.meta[myCorrelationId]
```
My preference here is to go to a string as the GUID can be reconstructed just with that one value. Thoughts?

**Comment by darko-mijic** [comment]
My strong preference is to go with string too.
