### ISSUE TITLE
Returning Space.Error from Router rather than null

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#94]
``` coffeescript
_handleDomainErrors: (fn) ->
    try
      return fn.call(this)
    catch error
      if error instanceof Space.Error
        this.publish(new Space.domain.Exception({
          thrower: @eventSourceable.toString(),
          error: error
        }))
        return null
      else
        throw error
```
We should really be returning the `Space.Error` after publishing, rather than [returning null](https://github.com/meteor-space/event-sourcing/blob/master/source/server/infrastructure/router.coffee#L103). While the original intent was rooted in CQRS theory, we're currently we're relying on subscription to the server-side event bus and specific implementation for pass this down into the client 👎

This is a bug IMO as an error is not a query response, it's negative acknowledgement (nack). 

Thoughts @meteor-space/core ?

**Comment by DominikGuzei** [comment]
Good call! 👍
